server:
  port: 80

spring:  application:    name: cloud-hystrix-feign-order

eureka:
  instance:
    instance-id: hystrix-feign-order-80   #配置服务注册的id
    prefer-ip-address: true  #是否公开注册服务的地址
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka  #配置eureka注册中心的地址
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

# 设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  # 指的是建立连接所用的时间,适用于网络状态正常的情况下,两端连接所用的时间
  ReadTimeout: 5000
  # 指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000 
 
feign:
  hystrix: 
    enabled: true
          
          
          
           
 
     